# fish completion for omp — generated by `omp completions fish`

function __fish_omp_no_subcommand
	for i in (commandline -opc)
		if contains -- $i acp agents auth-broker auth-gateway commit completions config grep grievances install plugin read search q setup shell ssh stats tiny-models update worktree wt
			return 1
		end
	end
	return 0
end

complete -c omp -f -n '__fish_omp_no_subcommand' -a 'acp' -d 'Run Oh My Pi as an ACP (Agent Client Protocol) server over stdio'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'agents' -d 'Manage bundled task agents'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'auth-broker' -d 'Manage the omp auth-broker (credential vault)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'auth-gateway' -d 'Run an auth-gateway forward proxy backed by the configured broker'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'commit' -d 'Generate a commit message and update changelogs'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'completions' -d 'Print a shell completion script (bash, zsh, or fish)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'config' -d 'Manage configuration settings'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'grep' -d 'Test grep tool'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'grievances' -d 'View, clean, or push reported tool issues (auto-QA grievances)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'install' -d 'Install or link an extension package (alias of `plugin install`/`plugin link`)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'plugin' -d 'Manage plugins (install, uninstall, list, etc.)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'read' -d 'Show what the read tool will return for a path or URL'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'search' -d 'Test web search providers'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'q' -d 'Test web search providers'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'setup' -d 'Run onboarding setup or install dependencies for optional features'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'shell' -d 'Interactive shell console'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'ssh' -d 'Manage SSH host configurations'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'stats' -d 'View usage statistics'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'tiny-models' -d 'Download tiny local models (session titles + memory)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'update' -d 'Check for and install updates'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'worktree' -d 'List or clear agent-managed git worktrees (~/.omp/wt)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'wt' -d 'List or clear agent-managed git worktrees (~/.omp/wt)'

complete -c omp -n '__fish_omp_no_subcommand' -l model -d 'Model to use (fuzzy match: "opus", "gpt-5.2", or "openai/gpt-5.2")' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l smol -d 'Smol/fast model for lightweight tasks (or PI_SMOL_MODEL env)' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l slow -d 'Slow/reasoning model for thorough analysis (or PI_SLOW_MODEL env)' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l plan -d 'Plan model for architectural planning (or PI_PLAN_MODEL env)' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l provider -d 'Provider to use (legacy; prefer --model)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l api-key -d 'API key (defaults to env vars)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l system-prompt -d 'System prompt (default: coding assistant prompt)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l append-system-prompt -d 'Append text or file contents to the system prompt' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l allow-home -d 'Allow starting in ~ without auto-switching to a temp dir'
complete -c omp -n '__fish_omp_no_subcommand' -l mode -d 'Output mode: text (default), json, rpc, or rpc-ui' -x -a 'text json rpc acp rpc-ui'
complete -c omp -n '__fish_omp_no_subcommand' -s p -l print -d 'Non-interactive mode: process prompt and exit'
complete -c omp -n '__fish_omp_no_subcommand' -s c -l continue -d 'Continue previous session'
complete -c omp -n '__fish_omp_no_subcommand' -s r -l resume -d 'Resume a session (by ID prefix, path, or picker if omitted)' -x -a '(command omp __complete sessions -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l session-dir -d 'Directory for session storage and lookup' -x -a '(__fish_complete_directories (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l no-session -d 'Don’t save session (ephemeral)'
complete -c omp -n '__fish_omp_no_subcommand' -l models -d 'Comma-separated model patterns for Ctrl+P cycling' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l no-tools -d 'Disable all built-in tools'
complete -c omp -n '__fish_omp_no_subcommand' -l no-lsp -d 'Disable LSP tools, formatting, and diagnostics'
complete -c omp -n '__fish_omp_no_subcommand' -l no-pty -d 'Disable PTY-based interactive bash execution'
complete -c omp -n '__fish_omp_no_subcommand' -l tools -d 'Comma-separated list of tools to enable (default: all)' -x -a 'read bash edit ast_grep ast_edit render_mermaid ask debug eval ssh github find search lsp inspect_image browser checkpoint rewind task job irc todo_write web_search search_tool_bm25 write memory_edit retain recall reflect'
complete -c omp -n '__fish_omp_no_subcommand' -l thinking -d 'Set thinking level: minimal, low, medium, high, xhigh' -x -a 'minimal low medium high xhigh'
complete -c omp -n '__fish_omp_no_subcommand' -l hook -d 'Load a hook/extension file (can be used multiple times)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -s e -l extension -d 'Load an extension file (can be used multiple times)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l no-extensions -d 'Disable extension discovery (explicit -e paths still work)'
complete -c omp -n '__fish_omp_no_subcommand' -l no-skills -d 'Disable skills discovery and loading'
complete -c omp -n '__fish_omp_no_subcommand' -l skills -d 'Comma-separated glob patterns to filter skills (e.g., git-*,docker)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l no-rules -d 'Disable rules discovery and loading'
complete -c omp -n '__fish_omp_no_subcommand' -l export -d 'Export session file to HTML and exit' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l list-models -d 'List available models (with optional fuzzy search)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l no-title -d 'Disable title auto-generation'
complete -c omp -n '__fish_omp_no_subcommand' -l auto-approve -d 'Auto-approve all tool calls (skip approval prompts)'
complete -c omp -n '__fish_omp_no_subcommand' -l approval-mode -d 'Override tools.approvalMode for this session (always-ask|write|yolo)' -x -a 'always-ask write yolo'

complete -c omp -n '__fish_seen_subcommand_from agents' -s f -l force -d 'Overwrite existing agent files'
complete -c omp -n '__fish_seen_subcommand_from agents' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from agents' -l dir -d 'Output directory (overrides --user/--project)' -r -F
complete -c omp -n '__fish_seen_subcommand_from agents' -l user -d 'Write to ~/.omp/agent/agents (default)'
complete -c omp -n '__fish_seen_subcommand_from agents' -l project -d 'Write to ./.omp/agents'
complete -c omp -f -n '__fish_seen_subcommand_from agents' -a 'unpack' -d 'Agents action'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -s b -l bind -d 'Bind address for `serve` (host:port)' -r -F
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l regenerate -d 'Regenerate the bearer token'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l via -d 'SSH user@host for remote login (login --via=user@host)' -r -F
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l provider -d 'Override provider id for `import` (e.g. when JSON `type` is unrecognized)' -r -F
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l include-disabled -d 'Import credentials whose JSON has `disabled: true` (import)'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l from-local -d 'migrate source: local SQLite + env vars (required for `migrate`)'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l include-env -d 'Capture env-var API keys for providers not yet on broker (migrate)'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l include-oauth -d 'Also upload OAuth from local SQLite during migrate (default skips them)'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l dry-run -d 'Print actions without executing (import / login --via / migrate)'
complete -c omp -f -n '__fish_seen_subcommand_from auth-broker' -a 'serve token login logout import migrate status list' -d 'Sub-command'
complete -c omp -n '__fish_seen_subcommand_from auth-gateway' -l json -d 'Output JSON (token/status/check)'
complete -c omp -n '__fish_seen_subcommand_from auth-gateway' -s b -l bind -d 'Bind address for `serve` (host:port)' -r -F
complete -c omp -n '__fish_seen_subcommand_from auth-gateway' -l regenerate -d 'Regenerate the gateway bearer token (token)'
complete -c omp -n '__fish_seen_subcommand_from auth-gateway' -l no-auth -d 'Disable inbound bearer-token auth (serve). Useful when bound to loopback — any caller is allowed.'
complete -c omp -n '__fish_seen_subcommand_from auth-gateway' -l strict -d 'For `check`: additionally probe each credential against its provider’s chat-completion endpoint. Slower; consumes a tiny amount of quota per credential.'
complete -c omp -f -n '__fish_seen_subcommand_from auth-gateway' -a 'serve token status check' -d 'Sub-command'
complete -c omp -n '__fish_seen_subcommand_from commit' -l push -d 'Push after committing'
complete -c omp -n '__fish_seen_subcommand_from commit' -l dry-run -d 'Preview without committing'
complete -c omp -n '__fish_seen_subcommand_from commit' -l no-changelog -d 'Skip changelog updates'
complete -c omp -n '__fish_seen_subcommand_from commit' -l legacy -d 'Use legacy deterministic pipeline'
complete -c omp -n '__fish_seen_subcommand_from commit' -s c -l context -d 'Additional context for the model' -r -F
complete -c omp -n '__fish_seen_subcommand_from commit' -s m -l model -d 'Override model selection' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -f -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish' -d 'Target shell'
complete -c omp -n '__fish_seen_subcommand_from config' -l json -d 'Output JSON'
complete -c omp -f -n '__fish_seen_subcommand_from config' -a 'list get set reset path init-xdg' -d 'Config action'
complete -c omp -n '__fish_seen_subcommand_from grep' -s g -l glob -d 'Filter files by glob pattern' -r -F
complete -c omp -n '__fish_seen_subcommand_from grep' -s l -l limit -d 'Max matches' -x
complete -c omp -n '__fish_seen_subcommand_from grep' -s C -l context -d 'Context lines' -x
complete -c omp -n '__fish_seen_subcommand_from grep' -s f -l files -d 'Output file names only'
complete -c omp -n '__fish_seen_subcommand_from grep' -s c -l count -d 'Output match counts per file'
complete -c omp -n '__fish_seen_subcommand_from grep' -l no-gitignore -d 'Include files excluded by .gitignore'
complete -c omp -F -n '__fish_seen_subcommand_from grep'
complete -c omp -n '__fish_seen_subcommand_from grievances' -s n -l limit -d 'Number of recent issues to show (list)' -x
complete -c omp -n '__fish_seen_subcommand_from grievances' -s t -l tool -d 'Filter by tool name (list, clean)' -r -F
complete -c omp -n '__fish_seen_subcommand_from grievances' -s j -l json -d 'Output as JSON'
complete -c omp -n '__fish_seen_subcommand_from grievances' -l id -d 'Delete a single grievance by id (clean)' -x
complete -c omp -n '__fish_seen_subcommand_from grievances' -l all -d 'Delete every grievance (clean)'
complete -c omp -f -n '__fish_seen_subcommand_from grievances' -a 'list clean push' -d 'list (default), clean, or push'
complete -c omp -n '__fish_seen_subcommand_from install' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from install' -l force -d 'Force install'
complete -c omp -n '__fish_seen_subcommand_from install' -l dry-run -d 'Show actions without applying changes'
complete -c omp -n '__fish_seen_subcommand_from install' -l scope -d 'Install scope: "user" (default) or "project" (marketplace installs only)' -x -a 'user project'
complete -c omp -F -n '__fish_seen_subcommand_from install'
complete -c omp -n '__fish_seen_subcommand_from plugin' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from plugin' -l fix -d 'Attempt to fix issues (doctor)'
complete -c omp -n '__fish_seen_subcommand_from plugin' -l force -d 'Force install'
complete -c omp -n '__fish_seen_subcommand_from plugin' -l dry-run -d 'Show actions without applying changes'
complete -c omp -n '__fish_seen_subcommand_from plugin' -s l -l local -d 'Operate on local plugin directory'
complete -c omp -n '__fish_seen_subcommand_from plugin' -l enable -d 'Enable a feature' -r -F
complete -c omp -n '__fish_seen_subcommand_from plugin' -l disable -d 'Disable a feature' -r -F
complete -c omp -n '__fish_seen_subcommand_from plugin' -l set -d 'Set plugin config (key=value)' -r -F
complete -c omp -n '__fish_seen_subcommand_from plugin' -l scope -d 'Install scope: "user" (default) or "project"' -x -a 'user project'
complete -c omp -f -n '__fish_seen_subcommand_from plugin' -a 'install uninstall list link doctor features config enable disable marketplace discover upgrade' -d 'Plugin action'
complete -c omp -F -n '__fish_seen_subcommand_from read'
complete -c omp -n '__fish_seen_subcommand_from search q' -l provider -d 'Search provider' -x -a 'auto tavily perplexity brave jina kimi anthropic gemini codex zai exa parallel kagi synthetic searxng'
complete -c omp -n '__fish_seen_subcommand_from search q' -l recency -d 'Recency filter' -x -a 'day week month year'
complete -c omp -n '__fish_seen_subcommand_from search q' -s l -l limit -d 'Max results to return' -x
complete -c omp -n '__fish_seen_subcommand_from search q' -l compact -d 'Render condensed output'
complete -c omp -F -n '__fish_seen_subcommand_from search q'
complete -c omp -n '__fish_seen_subcommand_from setup' -s c -l check -d 'Check if dependencies are installed'
complete -c omp -n '__fish_seen_subcommand_from setup' -l json -d 'Output status as JSON'
complete -c omp -f -n '__fish_seen_subcommand_from setup' -a 'python stt' -d 'Optional component to install'
complete -c omp -n '__fish_seen_subcommand_from shell' -s C -l cwd -d 'Set working directory for commands' -r -F
complete -c omp -n '__fish_seen_subcommand_from shell' -s t -l timeout -d 'Timeout per command in milliseconds' -x
complete -c omp -n '__fish_seen_subcommand_from shell' -l no-snapshot -d 'Skip sourcing snapshot from user shell'
complete -c omp -n '__fish_seen_subcommand_from ssh' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from ssh' -l host -d 'Host address' -r -F
complete -c omp -n '__fish_seen_subcommand_from ssh' -l user -d 'Username' -r -F
complete -c omp -n '__fish_seen_subcommand_from ssh' -l port -d 'Port number' -r -F
complete -c omp -n '__fish_seen_subcommand_from ssh' -l key -d 'Identity key path' -r -F
complete -c omp -n '__fish_seen_subcommand_from ssh' -l desc -d 'Host description' -r -F
complete -c omp -n '__fish_seen_subcommand_from ssh' -l compat -d 'Enable compatibility mode'
complete -c omp -n '__fish_seen_subcommand_from ssh' -l scope -d 'Config scope (project|user)' -x -a 'project user'
complete -c omp -f -n '__fish_seen_subcommand_from ssh' -a 'add remove list' -d 'SSH action'
complete -c omp -n '__fish_seen_subcommand_from stats' -s p -l port -d 'Port for the dashboard server' -x
complete -c omp -n '__fish_seen_subcommand_from stats' -s j -l json -d 'Output stats as JSON'
complete -c omp -n '__fish_seen_subcommand_from stats' -s s -l summary -d 'Print summary to console'
complete -c omp -n '__fish_seen_subcommand_from tiny-models' -l json -d 'Output JSON'
complete -c omp -f -n '__fish_seen_subcommand_from tiny-models' -a 'download list' -d 'Action to perform'
complete -c omp -n '__fish_seen_subcommand_from update' -s f -l force -d 'Force update'
complete -c omp -n '__fish_seen_subcommand_from update' -s c -l check -d 'Check for updates without installing'
complete -c omp -n '__fish_seen_subcommand_from worktree wt' -l all -d 'Clear every entry, including live PR-checkout worktrees (clear)'
complete -c omp -n '__fish_seen_subcommand_from worktree wt' -s n -l dry-run -d 'Print what would be removed without touching the filesystem (clear)'
complete -c omp -n '__fish_seen_subcommand_from worktree wt' -s j -l json -d 'Emit machine-readable JSON'
complete -c omp -f -n '__fish_seen_subcommand_from worktree wt' -a 'list clear' -d 'list (default) or clear'

